SAP/cap-operator

- website/content/en/docs/_index.md
- website/content/en/docs/concepts/operator-components/_index.md
- website/content/en/docs/concepts/operator-components/controller.md
- website/content/en/docs/concepts/operator-components/subscription-server.md
- website/content/en/docs/usage/tenant-provisioning.md
Point to the right image path based on the public url.
Change-Id: I2e5a21d513d0dc7eddfffa3697a113b6f7eaa015
> [Misc] CAP Operator: website image path updated

- README.md
> [Misc] CAP Operator: Reuse compliant badge added

- README.md
> [Misc] Operator: Badges added

- README.md
- cmd/server/internal/handler.go
- internal/controller/reconcile-capapplicationversion.go
- sonar-project.properties
- website/content/en/_index.md
- website/content/en/docs/usage/resources/capapplication.md
- website/content/en/docs/usage/resources/capapplicationversion.md
> [Misc] website: Badges added

- README.md
- website/content/en/_index.md
- Update link in sonar badge to point to overall summary page!
> [Misc] Readme: Misc stuff updated

- .github/workflows/publish-docker
- .github/workflows/publish.yaml
- Generate and upload crd.yaml as release artifact
- Update docker workflow to be triggered on `semver` tag push
> [Misc] workflows: publish and docker workflows (Release) updated

- website/includes/api-reference.html
regenerate with latest version
> [Misc] website: API reference update

- website/content/en/docs/installation/cap-operator-manager/_index.md
- website/content/en/docs/installation/cap-operator-manager/kyma-cluster.md
- website/content/en/docs/installation/cap-operator-manager/local-cluster.md
Added installation steps using CAP Operator manager in Kyma/Local cluster.
Website final look - https://anirudhprasad-sap.github.io/cap-operator/docs/
> [Docs] Added installation steps using CAP Operator manager in Kyma/Local cluster

- README.md
- pkg/apis/sme.sap.com/v1alpha1/types.go
- website/includes/api-reference.html
- Correct path to chart
- api docu corrections
Change-Id: Ib77bf0bb83ca86b475331f6e73f3edb042a14ec8
> [Misc] Docu: minor issues corrected

- website/content/en/docs/usage/resources/captenant.md
This should be never instead of none!
Resolves: #53
> [Misc] website docu: Upgrade strategy value corrected

- website/content/en/docs/usage/deploying-application.md
- website/content/en/docs/usage/resources/capapplicationversion.md
- Mention explicitly that CAV is immutable
- Fix default port of approuter in docu (code already used 5000)
> [Misc] Operator: Docu updated

- internal/controller/reconcile-capapplication.go
- internal/controller/reconcile-capapplication_test.go
- internal/controller/reconcile.go
- internal/controller/testdata/capapplication/ca-19.expected.yaml
- internal/controller/testdata/capapplication/ca-29.expected.yaml
- internal/controller/testdata/common/credential-secrets.yaml
Preseve secrets mentioned in the CAPApplication by adding a finalizer.
Resolves:
JIRA: ERP4SMEPREPWORKAPPPLAT-7268
> [FEATURE] Operator: Preserving Secrets implemented

- internal/controller/reconcile-domains.go
sanitize dns target to get rid of asterix:
*.domain replaced with x.domain
> [FIX] Operator: DNSEntry handling amended

- go.mod
- go.sum
- Use latest version of Go
- Use latest version of Go dependencies
> [Misc] Operator: Go Dependencies updated

- internal/controller/reconcile-domains.go
- internal/controller/reconcile-domains_test.go
- internal/controller/utils.go
- website/includes/chart-values.md
Allow consumers to configure a DNS_TARGET via env. on controller.
> [FEATURE] Operator: DNS_TARGET via env. supported

- .github/workflows/build.yml
- .github/workflows/publish-docker.yaml
- .github/workflows/publish-website.yaml
Update workflows to the latest version
> [Misc] workflows: update to the latest version

- .github/workflows/publish-website.yaml
- website/content/en/_index.md
- website/go.mod
- website/go.sum
- website/hugo.yaml
- website/package-lock.json
- website/package.json
- Update to the latest version
- Minor fixes to overall content
> [Misc] Operator (website): latest version used

- go.mod
- go.sum
Update to the latest version of Go dependencies.
> [Misc] Operator: Dependencies updated

- crds/sme.sap.com_capapplications.yaml
- crds/sme.sap.com_capapplicationversions.yaml
- crds/sme.sap.com_captenantoperations.yaml
- crds/sme.sap.com_captenants.yaml
- internal/controller/reconcile-capapplicationversion.go
- internal/controller/reconcile-capapplicationversion_test.go
- internal/controller/reconcile-captenantoperation.go
- internal/controller/reconcile-captenantoperation_test.go
- internal/controller/testdata/capapplicationversion/cav-init.yaml
- internal/controller/testdata/capapplicationversion/expected/cav-ready-init.yaml
- internal/controller/testdata/captenantoperation/ctop-init-custom.expected.yaml
- internal/controller/testdata/captenantoperation/ctop-init-custom.initial.yaml
- internal/controller/testdata/captenantoperation/ctop-init.expected.yaml
- internal/controller/testdata/captenantoperation/ctop-init.initial.yaml
- internal/controller/testdata/common/capapplicationversion-v1-init-custom.yaml
- internal/controller/testdata/common/capapplicationversion-v1-init.yaml
- pkg/apis/sme.sap.com/v1alpha1/types.go
- pkg/apis/sme.sap.com/v1alpha1/zz_generated.deepcopy.go
- pkg/client/applyconfiguration/sme.sap.com/v1alpha1/capapplicationstatus.go
- pkg/client/applyconfiguration/sme.sap.com/v1alpha1/capapplicationversionstatus.go
- pkg/client/applyconfiguration/sme.sap.com/v1alpha1/captenantoperationstatus.go
- pkg/client/applyconfiguration/sme.sap.com/v1alpha1/captenantstatus.go
- pkg/client/applyconfiguration/sme.sap.com/v1alpha1/commondetails.go
- pkg/client/applyconfiguration/sme.sap.com/v1alpha1/deploymentdetails.go
- pkg/client/applyconfiguration/sme.sap.com/v1alpha1/genericstatus.go
- pkg/client/applyconfiguration/sme.sap.com/v1alpha1/jobdetails.go
- website/includes/api-reference.html
Support initContainers for all workloads
Resolves:
JIRA: ERP4SMEPREPWORKAPPPLAT-7450
Fixes: https://github.com/SAP/cap-operator/issues/64
> [FEATURE] Operator: initContainers supported

- website/go.mod
> [Misc] website: Go version updated

- cmd/server/internal/handler.go
- cmd/server/internal/handler_test.go
- internal/controller/reconcile-capapplication.go
- internal/controller/reconcile-capapplicationversion.go
- internal/controller/reconcile-captenant.go
- internal/controller/reconcile-captenantoperation.go
- internal/controller/reconcile-domains.go
- internal/controller/reconcile.go
- internal/util/config.go
- internal/util/log.go
- internal/util/log_test.go
Add a "step" to the log wherever possible.
This may be used later to filter the logs accordingly.
> [Misc] Operator: logs (step) enriched

- internal/controller/reconcile-domains.go
reconcilation --> reconciliation
> [Misc] Operator: misc typo fixed

- .github/workflows/publish-website.yaml
- website/content/en/docs/concepts/_index.md
- website/content/en/docs/usage/deploying-application.md
- website/content/en/docs/usage/version-upgrade.md
- website/package-lock.json
- website/package.json
- use latest version
- attempt to fix by updating links to remove {{ref}}
> [Misc] website: update website build + links in docu

- go.mod
- go.sum
- website/hugo.yaml
- website/package-lock.json
- website/package.json
- update dependencies
- update website config
> [Misc] Operator: website / misc. deps updated

- CONTRIBUTING.md
Reference to guideline for AI-generated code contributions to SAP Open Source Software Projects
> [README] Contributing with AI-generated code referenced

- .github/workflows/publish-website.yaml
- website/assets/scss/_styles_project.scss
- website/content/en/_index.md
- website/content/en/docs/configuration/_index.md
- website/content/en/docs/usage/resources/_index.md
- website/content/en/docs/usage/resources/capapplicationversion.md
- website/content/en/docs/usage/version-monitoring.md
- website/go.mod
- website/go.sum
- website/hugo.yaml
- website/includes/api-reference.html
- website/includes/chart-values.md
- website/package-lock.json
- website/package.json
- website/static/img/activity-tenantprovisioning.drawio.svg
- website/static/img/block-cluster.drawio.svg
- website/static/img/block-controller.drawio.svg
- website/static/img/block-subscription.drawio.svg
CHANGES:
- updated `hugo` modules
- enabled dark mode support (from `docsy`)
- added page related to version monitoring
- generated relevat API Reference docs and Helm chart docs
> [website] update docsy + added version monitoring docs

- internal/controller/reconcile-capapplicationversion.go
- internal/controller/reconcile.go
- internal/controller/version-monitoring.go
CHANGES:
- refactor version monitoring related methods to reduce cognitive complexity
> [FIX] recent sonar issues

- cmd/web-hooks/internal/handler/handler.go
Get rid of unnecessary beta API usage.
> [Misc] Operator: webhook - Right api version used

- .github/workflows/publish-website.yaml
- website/content/en/docs/installation/helm/_index.md
- website/content/en/docs/installation/prerequisites.md
- website/content/en/docs/support/_index.md
- website/content/en/docs/troubleshoot/_index.md
- website/content/en/docs/usage/tenant-provisioning.md
- website/content/en/docs/whats-new.md
- website/go.mod
- website/go.sum
- website/package-lock.json
- update dependencies
- cleanup/address minor issues
> [Misc] Operator: website deps/content updated

- website/content/en/docs/installation/helm/_index.md
- website/content/en/docs/usage/operator-metrics.md
- website/content/en/docs/usage/prerequisites.md
- website/content/en/docs/whats-new.md
Misc improvements to some documentation.
Mainly operator metrics part and some anchors.
> [Docu] website: Documentation enhanced

- website/hugo.yaml
Use range specifying the start year.
> [Misc] website: copyright updated

- cmd/server/internal/jwt.go
- go.mod
- go.sum
Migrate to github.com/MicahParks/keyfunc/v3
- Needs new jwkset module to be included
> [Misc] Operator: jwt validation dependants updated

- internal/controller/certificate-handler.go
- internal/controller/reconcile-domain.go
Add missing License and fix minor comment typo
> Minor fixes

- cmd/web-hooks/internal/handler/handler.go
> [webhook] Domain namespace check removed

- internal/controller/certificate-handler.go
- internal/controller/reconcile-domain.go
- internal/controller/reconcile-networking.go
- Replace Asterix (* --> x) 
- Add explicit CommonName to certificate by trimming to 64 chars
Also:
- Remove some unused code.
> fixes for domain / dns

- internal/controller/certificate-handler.go
Revert the change for now.
Fix TBD
> [Misc] Revert 64 char limit based CN for now

- .github/workflows/publish.yaml
> [Misc] Workflow: permissions for Release assets added

- build/controller/Dockerfile
- build/server/Dockerfile
- build/web-hooks/Dockerfile
Speed up the builds in pipeline by using same build platform for `amd64` and `arm64`.
> [Misc] Pipeline: Multi-arch builds improved

- cmd/controller/domain-migration.go
- internal/controller/reconcile-domain_test.go
- internal/util/uaa_test.go
- Fix/Update missing license
- Rename domain test
> [Misc] Fix missing licenses

- cmd/web-hooks/internal/handler/mutate.go
- cmd/web-hooks/internal/handler/mutate_test.go
- cmd/web-hooks/main.go
- go.mod
- go.sum
Implemented mutation webhook to migrate from domains to domainRefs.
> [FEAT] Mutation webhook added

- cmd/controller/domain-migration.go
- internal/controller/certificate-handler.go
- internal/controller/reconcile-capapplication.go
- internal/controller/reconcile-domain.go
- internal/controller/reconcile-networking.go
- Move IngressInfo code to one place
- Remove unused code/comments
> [Misc] Cleanup: Networking code reorganized

- website/content/en/docs/troubleshoot/_index.md
- website/content/en/docs/usage/deploying-application.md
- website/content/en/docs/usage/domain-management.md
- website/content/en/docs/usage/resources/capapplicationversion.md
- website/content/en/docs/usage/version-upgrade.md
> [Misc] Docu updates

- cmd/server/internal/handler.go
- cmd/server/internal/handler_test.go
- pkg/apis/sme.sap.com/v1alpha1/types.go
Use the new DomainRefs to return the correct app subscription URL to BTP saas services.
> [Misc] Subscription callback url:  DomainRefs used

- internal/controller/reconcile-captenant_test.go
- internal/controller/reconcile-networking.go
- internal/controller/reconcile.go
- internal/controller/testdata/captenant/cat-30.expected.yaml
- internal/controller/testdata/captenant/cat-30.initial.yaml
- internal/controller/testdata/common/capapplication-vs-headers-error-req.yaml
- internal/controller/testdata/common/capapplication-vs-headers-error-res.yaml
- internal/controller/testdata/common/capapplication-vs-headers.yaml
Set request/response headers in a VS route via CA annotations.
> [Misc] VS: Headers (Set) via annotation supported

- internal/controller/certificate-manager.go
- internal/controller/reconcile-domain.go
> [Misc] Operator: Certificate handling refactored

- cmd/web-hooks/internal/handler/handler.go
- cmd/web-hooks/internal/handler/mutate_test.go
- internal/controller/reconcile-capapplication.go
- internal/controller/reconcile-capapplicationversion.go
- internal/controller/reconcile-captenant.go
- internal/controller/reconcile-captenantoperation.go
- internal/controller/reconcile-networking.go
- internal/controller/reconcile.go
> [Misc] Operator: Code Refactored

- .github/workflows/publish-docker.yaml
- .github/workflows/publish.yaml
Generate sbom release artifacts for cap operator images
> [FEAT] Release: SBOM artifacts added
